name: "Publish Release"
description: "Publishes a release to Github and npm"

inputs:
  branchName:
    description: 'The branch name of from which this release was triggered'
    required: false
    default: 'latest'
  githubToken:
    description: 'The Github auth token'
    required: false
    default: 'latest'
  npmToken:
    description: 'The npm auth token'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Project
      uses: ./.github/actions/setup

    - name: Build Project
      run: npm run build
      shell: bash

    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
      run: npx semantic-release
      shell: bash

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npmToken }}
      run: npm publish ./dist/*.tgz --tag ${{ inputs.tag }}
      shell: bash
